//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembros
    {
        public int ID { get; set; }
        public string nombre_miembro { get; set; }
        public int id_asig { get; set; }
        public int estado_asig { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
