//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public int ID { get; set; }
        public string nombre_miembro { get; set; }
        public int id_asig { get; set; }
        public int estado_asig { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
